### ISSUE TITLE
Change order

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsSalesPage#13]
![image](https://user-images.githubusercontent.com/46600362/91315067-84b97700-e7b7-11ea-86c4-448aceaf410a.png)

- [ ] Change the order in this row;  "Applicatie" first.
- [ ] Also with the parts below; move "Applicatie" tot top (above "Gevelscan")
- [ ] Add pagelink for "Applicatie", like "gevelscan" ed.

**Comment by pnobbe** [comment]
> * [ ]  Add pagelink for "Applicatie", like "gevelscan" ed.

Die had het ook moeten doen, maarja....

![image](https://user-images.githubusercontent.com/8037254/92119052-932b1280-edf7-11ea-8a2c-1aac382b793b.png)

@DonZandbergen
